// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CPictureDisp wrapper class

class CPictureDisp : public COleDispatchDriver
{
public:
	CPictureDisp() {}		// Calls COleDispatchDriver default constructor
	CPictureDisp(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CPictureDisp(const CPictureDisp& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
};
