#if !defined(AFX_PICTUREDISP1_H__0E65818C_0078_420A_A506_27F301BABD2E__INCLUDED_)
#define AFX_PICTUREDISP1_H__0E65818C_0078_420A_A506_27F301BABD2E__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CPictureDisp1 wrapper class

class CPictureDisp1 : public COleDispatchDriver
{
public:
	CPictureDisp1() {}		// Calls COleDispatchDriver default constructor
	CPictureDisp1(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CPictureDisp1(const CPictureDisp1& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PICTUREDISP1_H__0E65818C_0078_420A_A506_27F301BABD2E__INCLUDED_)
